<?php

/**
 * @file
 * Implementation of module_a.
 */

/**
 * Implements hook_entity_info().
 */
function module_a_entity_info() {
  $return = array(
    'vehicle' => array(
      'label' => t('Vehicle'),
      'controller class' => 'VehicleController',
      'base table' => 'vehicle',
      'revision table' => 'vehicle_revision',
      'uri callback' => 'vehicle_uri',
      'fieldable' => TRUE,
      'translation' => array(
        'locale' => TRUE,
      ),
      'entity keys' => array(
        'id' => 'vhid',
        'revision' => 'vid',
        'bundle' => 'type',
        'language' => 'language',
      ),
      'bundle keys' => array(
        'bundle' => 'type',
      ),
      'bundles' => array(),
      'view modes' => array(),
    ),
  );
  $types = _module_a_get_vehicles_types();
  foreach ($types as $type) {
    $return['vehicle']['bundles'][$type] = array(
      'label' => t('@type', array('@type' => $type)),
      'uri callback' => 'vehicle_uri',
      'admin' => array(
        'path' => 'admin/structure/vehicles/manage/%vehicle_type',
        'real path' => 'admin/structure/vehicles/manage/' . $type,
        'bundle argument' => 4,
        'access arguments' => ['administer content types'],
      ),
    );
  }

  return $return;
}

/**
 * Implements hook_menu().
 */
function module_a_menu() {
  // Manage every vehicle type.
  $items['admin/structure/vehicles/manage/%vehicle_type'] = array(
    'title callback' => 'module_a_title_callback',
    'title arguments' => array(4, 'manage'),
    'page callback' => 'module_a_list_vehicle_type',
    'acces arguments' => array('administer content types'),
  );

  // Manage all vehicles.
  $items['admin/content/vehicles/manage'] = array(
    'title' => 'Manage vehicles',
    'description' => 'List of vehicles to manage.',
    'page callback' => 'module_a_list_vehicles',
    'access arguments' => array('administer content types'),
  );

  // Add vehicule.
  $items['admin/content/vehicles/add'] = array(
    'title' => 'Vehicle',
    'description' => 'Add vehicle.',
    'page callback' => 'module_a_add_vehicle_overview',
    'access arguments' => array('administer content types'),
    'type' => MENU_CALLBACK,
  );

  $types = _module_a_get_vehicles_types();
  foreach ($types as $type) {
    $item_path = 'admin/content/vehicles/add/' . $type;
    $items[$item_path] = array(
      'title' => drupal_ucfirst($type),
      'description' => 'Add vehicle.',
      'page callback' => 'module_a_add_vehicle',
      'page arguments' => array(4),
      'access arguments' => array('administer content types'),
    );
  }

  return $items;
}

/**
 * Page callback implementation for add vehicle overview.
 */
function module_a_add_vehicle_overview() {
  return 'none';
}

/**
 * @file
 * Page callback implementation for adding new vehicle.
 */
function module_a_add_vehicle($type) {
  return 'testing ading vehicle case';
}


/**
 * Page callback implementation to list vehicles.
 */
function module_a_list_vehicles() {
  // Load vehicles
  // Return them.

  return 'testing';
}

/**
 * Page callback Implementation to list vehicles of same type.
 */
function module_a_list_vehicle_types($arg) {
  // Load vehicle by type given in args.
  // Return entities.
}

/**

 * Get vehicles types.
 */
function _module_a_get_vehicles_types() {
  return array('car', 'van', 'truck');
}

/**
 * Implements the uri callback.
 */
function module_a_vehicle_uri($vehicle) {
  return array(
    'path' => 'vahicles/' . $vehicle->vhid,
  );
}

/**
 * Class VehicleController.
 */
class VehicleController extends DrupalDefaultEntityController {
}
